#!/bin/bash

args=("$@")

in=`echo ${args[0]} | tr '[:upper:]' '[:lower:]'`
declare -a CEIPS=('ce01-htc.cr.cnaf.infn.it' 'ce02-htc.cr.cnaf.infn.it' 'ce03-htc.cr.cnaf.infn.it' 'ce04-htc.cr.cnaf.infn.it' 'ce05-htc.cr.cnaf.infn.it' 'ce06-htc.cr.cnaf.infn.it' 'ce07-htc.cr.cnaf.infn.it' 'tier2-ce2.lnf.infn.it')
CEIP=${CEIPS[1]}
declare -a OWNERS=('cygno001' 'cygno002' 'cygno003' 'cygno004' 'cygno005' 'cygno006' 'cygno007' 'cygno')
OWNER=${OWNER[1]}

if [ -z "${FILETOKEN}" ]; then
    FILETOKEN="/tmp/token"
fi

if [ -z "${BEARER_TOKEN}" ]; then
    export BEARER_TOKEN=`cat ${FILETOKEN}`
fi

export _condor_SEC_CLIENT_AUTHENTICATION_METHODS=SCITOKENS

if [ "$in" == "--tier1" ] || [ "$in" == "-t" ]; then
    echo "Enabling htc@tier1"
    export SINGULARITY=true
    export CONDOR_CONFIG=/dev/null
elif [ "$in" == "--cloud" ] || [ "$in" == "-c" ]; then 
    echo "Enabling htc@cloud"
    unset SINGULARITY
    unset CONDOR_CONFIG
elif [ "$in" == "--monitor" ] || [ "$in" == "-q" ]; then
    if [ "$#" -gt 1 ]; then
        idce=$[${args[1]}-1]
        CEIP=${CEIPS[idce]}
    fi
    if [ -z "$CONDOR_CONFIG" ]; then
        echo "htc@cloud"
        condor_q -all
    else
        echo "htc@tier1"
        condor_q -pool $CEIP:9619 -name $CEIP
    fi
elif [ "$in" == "--myjobs" ] || [ "$in" == "-m" ]; then
    if [ "$#" -gt 1 ]; then
        idce=$[${args[1]}-1]
        CEIP=${CEIPS[idce]}
        OWNER=${OWNERS[idce]}
    fi
    if [ -z "$CONDOR_CONFIG" ]; then
        echo "htc@cloud"
        condor_q -all -format "ClusterID: %d " ClusterId -format "JobStatus: %d " JobStatus -format "CygnoUser: %s\n" CygnoUser | grep $USERNAME
    else
        echo "htc@tier1"
        condor_q -pool $CEIP:9619 -name $CEIP $OWNER -format "ClusterID: %d " ClusterId -format "JobStatus: %d " JobStatus -format "CygnoUser: %s\n" CygnoUser | grep $USERNAME
    fi

elif [ "$in" == "--jobs" ] || [ "$in" == "-j" ]; then
    if [ "$#" -gt 1 ]; then
        idce=$[${args[1]}-1]
        CEIP=${CEIPS[idce]}
        OWNER=${OWNERS[idce]}
    fi
    if [ -z "$CONDOR_CONFIG" ]; then
        echo "htc@cloud"
        condor_q -all -format "-----------------------------------------\n\nClusterID: %d\n" ClusterId -format "JobStatus: %d\n" JobStatus -format "CygnoUser: %s\n\n" CygnoUser
    else
        echo "htc@tier1"
        condor_q -pool $CEIP:9619 -name $CEIP $OWNER -format "-----------------------------------------\n\nClusterID: %d\n" ClusterId -format "JobStatus: %d\n" JobStatus -format "CygnoUser: %s\n\n" CygnoUser
    fi

elif [ "$in" == "--submit" ] || [ "$in" == "-s" ]; then
    if [ "$#" -gt 2 ]; then
        idce=$[${args[2]}-1]
        CEIP=${CEIPS[idce]}
    fi
    if [ -z "$CONDOR_CONFIG" ]; then
        echo "htc@cloud"
        condor_submit -spool ${args[1]}

    else
        echo "htc@tier1"
        condor_submit -spool ${args[1]} -pool $CEIP:9619 -name $CEIP 
    fi
elif [ "$in" == "--tranfer" ] || [ "$in" == "-f" ]; then
    if [ "$#" -gt 2 ]; then
        idce=$[${args[2]}-1]
        CEIP=${CEIPS[idce]}
    fi
    if [ -z "$CONDOR_CONFIG" ]; then
        echo "htc@cloud"
        condor_transfer_data ${args[1]}

    else
        echo "htc@tier1"
        condor_transfer_data ${args[1]} -pool $CEIP:9619 -name $CEIP  
    fi
elif [ "$in" == "--remove" ] || [ "$in" == "-r" ]; then
    if [ "$#" -gt 2 ]; then
        idce=$[${args[2]}-1]
        CEIP=${CEIPS[idce]}
    fi
    if [ -z "$CONDOR_CONFIG" ]; then
        echo "htc@cloud"
        condor_rm -forcex ${args[1]}

    else
        echo "htc@tier1"
        condor_rm -forcex ${args[1]} -pool $CEIP:9619 -name $CEIP  
    fi
elif [ "$in" == "--help" ] || [ "$in" == "-h" ] || [ -z "$in" ]; then
#elif [ [ "$in" == "--help"] || [ "$in" == "-h"] || [ ! -z "$in"  ] ]; then
    echo "Usage:"
    echo "  -t/-c --tier1/--cloud, configure/switch between htc@tier1 and htc@cloud" 
    echo "  -s --submit, submit a job:  -s <subfilename> <ceid> [only for tier1 ceid=1-7 default ce02]"
    echo "  -f --tranfer, tranfer files: -f <jobid> <ceid> [only for tier1 ceid=1-7 default ce02]"
    echo "  -r --remove, remove jobs: -r <jobid> <ceid> [only for tier1 ceid=1-7 default ce02]"
    echo "  -q --monitor, monitor jobs: -q <ceid> [only for tier1 ceid=1-7 default ce02]"
    echo "  -m --myjobs, monitor my jobs (${USERNAME}): -m <ceid> [only for tier1 ceid=1-7 default ce02]"
    echo "  -j --jobs, monitor all jobs: -j <ceid> [only for tier1 ceid=1-7 default ce02]"
    echo "  -h --help, show this help"
fi
